### ISSUE TITLE
`cp` doesn't work on `build:rust` in linux build from source

### ISSUE THREAD

**Issue by jared-hughes** [unageek/graphest#779]
## Summary

`npm start` builds the webpack + rust code properly but gives the error

```
cp: cannot stat 'target/release/{compose,concatenate,graph}': No such file or directory
ERROR: "build:rust" exited with 1.
```

After running `npx electron .`, the UI works, but the backend doesn't, so no graphs appear in the viewport

## Workaround

```
npm run build; cp target/release/{compose,concatenate,graph} dist/ && npx electron .
```

## Details

Clean build after `rm -rf`ing `target` and `dist` directories:

```
● ~/graphest$ npm run start

> graphest@1.2.1 start
> cross-env-shell NODE_ENV=development npm run build && electron .


> graphest@1.2.1 build
> npm-run-all build:*


> graphest@1.2.1 build:app
> webpack

webpack compiled successfully

webpack compiled successfully

webpack compiled successfully

> graphest@1.2.1 build:rust
> cargo build --release && mkdirp dist && rm -f dist/{compose,concatenate,graph} && cp target/release/{compose,concatenate,graph} dist/

   Compiling autocfg v1.0.1
   Compiling libc v0.2.101
   Compiling memchr v2.4.1
// (more compiles omitted)
   Compiling inari v0.15.0
   Compiling graphest-fftw-sys v0.1.0 (/home/jared/graphest/rust/graphest-fftw-sys)
   Compiling graphest-arb-sys v0.5.0 (/home/jared/graphest/rust/graphest-arb-sys)
   Compiling graphest v1.2.1 (/home/jared/graphest/rust)
    Finished release [optimized] target(s) in 1m 38s
cp: cannot stat 'target/release/{compose,concatenate,graph}': No such file or directory
ERROR: "build:rust" exited with 1.
● ~/graphest$ ls target/release/{compose,concatenate,graph}
target/release/compose  target/release/concatenate  target/release/graph
```

The webpack and UI works; I can run `npx electron .` to get the full UI. But nothing shows on the plot; the backend doesn't work

```
APPIMAGE env is not defined, current application is not an AppImage
checkForUpdatesAndNotify called, downloadPromise is null
Error occurred in handler for 'request-relation': TypeError: Cannot read properties of undefined (reading 'match')
    at /home/jared/graphest/dist/main.js:72181:45
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async node:electron/js2c/browser_init:189:563
Error occurred in handler for 'request-relation': TypeError: Cannot read properties of undefined (reading 'match')
    at /home/jared/graphest/dist/main.js:72181:45
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async node:electron/js2c/browser_init:189:563
```

## Fix attempt

Changing the one line in package.json to
```json
    "build:rust": "cargo build --release && mkdirp dist && rm -f dist/{compose,concatenate,graph} && sleep 1 && cp target/release/{compose,concatenate,graph} dist/",
```
does not work

## System

```
● ~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
● ~$ rustc --version
rustc 1.61.0 (fe5b13d68 2022-05-18)
● ~$ node --version
v16.15.1
● ~$ npm --version
8.11.0
```

**Comment by unageek** [comment]
This is fixed in 8a47c78cd25e6e5ed9bead8556442e47ccc2ae19.

I am sorry, but I had to force-push the `main` branch. Now, the history after 2c87d4dafaa8e64639c32a83fbd55bca73680e20 must be different from yours. Please check out the branch again.
